FROM ubuntu:latest
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    python-pip \
    python-dev \
    build-essential
COPY . /app
WORKDIR /app
RUN pip install --upgrade setuptools && pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
